name: enveronment Variables

on:
  push:
  workflow_dispatch:

env:
  workflow_env: "boom boom"

jobs:
  first-job:
    env:
      job_env: "tricky job"

    steps:
      - env:
          step_env: "fluffy doll"
        run: echo $workflow_env
      - run: echo $job_env
      - run: echo $step_env
